# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'cocoapods-consumer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'spm-study', git: "https://github.com/didisouzacosta/spm-study.git"

end
